version: 2
sources:
  - name: raw
    description: "gwz_raw_data"
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        columns:
          - name: date_date
          - name: orders_id
          - name: pdt_id
          - name: revenue
          - name: quantity
      - name: product
        identifier: raw_gz_product
        description: list of products by product id with purchase price
        columns:
          - name: products_id
            description: "pk"
            tests:
              - unique
              - not_null
          - name: purchSE_PRICE
      - name: ship
        identifier: raw_gz_ship
        description: order id with shipping fee, logistic cost and shipping cost
        columns:
          - name: orders_id
            description: "pk"
            tests:
              - unique
              - not_null
          - name: shipping_fee
          - name: shipping_fee_1
          - name: logCost
          - name: ship_cost
      - name: adwords
        identifier: raw_gz_adwords
        description: ads and costs
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
      - name: bing
        identifier: raw_gz_bing
        description: bing data
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
      - name: criteo
        identifier: raw_gz_criteo
        description: criteo data
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
      - name: facebook
        identifier: raw_gz_facebook
        description: facebook data
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click